# Description: This class contains the list of supported themes for the application

class SupportedThemes:
    def __init__(self):
        pass

    @staticmethod
    def list_of_supported_themes():
        supported_themes = [
            'Adutoras_SNIRH_ANA_2021',
            'Aerodromos_ANAC_2022',
            'Aerogeradores_ANEEL_2023',
            'APCB_Amazonia',
            'APCB_Caatinga',
            'APCB_Cerrado_Pantanal',
            'APCB_Mata_Atlantica',
            'APCB_ZonaCosteira',
            'Aves_Migratorias_Areas_Ameacadas_CEMAVE_2022',
            'Aves_Migratorias_Areas_Concentracao_CEMAVE_2022',
            'Bases_de_Combustíveis_EPE',
            'Bases_de_GLP_EPE',
            'Biomas_IBGE_2019_250000',
            'Blocos_Disponiveis_OPC_1009_ANP',
            'Cavidades_CANIE_2022',
            'Centrais_Geradoras_Hidrelétricas_CGH_ANEEL',
            'CGH_Base_Existente_EPE',
            'CGH_Expansao_Planejada_EPE',
            'Conservacao_Aves_IBAS',
            'Dutos_de_escoamento_EPE',
            'Dutovias_MINFRA_2018',
            'EOL_Base_Existente_EPE',
            'EOL_Expansao_Planejada_EPE',
            'Ferrovias_MINFRA',
            'Gasodutos_de_distribuição_EPE_2023',
            'Gasodutos_de_transporte_EPE_2023',
            'Geologia_IBGE',
            'Geomorfologia_IBGE',
            'Hidrovias_ANTAQ',
            'IBAs_MataAtlantica_SaveBrasil_2023',
            'Lei_Mata_Atlantica_MMA',
            'Localidades_IBGE_2010',
            'LT_Existente_EPE_2023',
            'LT_Planejada_EPE_2023',
            'Municipios_IBGE_2022',
            'Ocorrencias_Fossiliferas_CPRM',
            'PCH_Base_Existente_EPE_2023',
            'PCH_Expansao_Planejada_EPE_2023',
            'Pedologia_IBGE',
            'Pequenas_Centrais_Hidrelétricas_PCH_ANEEL',
            'Pivo_Central_Irrigacao_ANA_2019',
            'Plantas_de_biodiesel_EPE',
            'Plantas_de_etanol_EPE',
            'Polos_de_processamento_de_gás_natural_EPE',
            'Potencial_Cavidades_ICMBio',
            'Reserva_Biodiversidade_Mata_Atlantica_RBMA',
            'Rodovia_Estadual_DNIT',
            'Rodovia_Federal_DNIT',
            'RPPNs_ICMBio',
            'Sitios_Arqueologicos_IPHAN',
            'Subestacoes_Base_Existente_EPE_2023',
            'Subestacoes_Expansao_Planejada_EPE_2023',
            'Terminais_de_Petroleo_e_Derivados_EPE',
            'Territorios_Quilombolas_INCRA_2023',
            'Terras_Indigenas_FUNAI',
            'Trecho_Drenagem_ANA_2013',
            'UHE_Base_Existente_EPE_2023',
            'Unidades_de_Conservacao_MMA',
            'Usina_Fotovoltaica_UFV_ANEEL_2023',
            'Usina_Termeletricas_UTE_ANEEL_2023',
            'Usinas_Hidrelétricas_UHE_ANEEL_2023',
            'UTE_Biomassa_Existente_EPE_2023',
            'Vegetacao_IBGE',
            'Vilas_IBGE_2021',
            'Areas_Quilombolas_INCRA',
            'Areas_Urbanizadas_IBGE_2019',
            'Assentamentos_INCRA',
            'Processos_Minerarios_ANM',
            'Capitais',
            'Sedes_municipais']
        return supported_themes